cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false

application:
  bucket:
    name: myawsbucket-3

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9090